// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBTZCGT4VHZFBw5JQmFQqpACq33GPFlqQ',
    appId: '1:701759991705:web:5c9e1cec939f1c4d5bad08',
    messagingSenderId: '701759991705',
    projectId: 'b2b-partnership-47ae1',
    authDomain: 'b2b-partnership-47ae1.firebaseapp.com',
    storageBucket: 'b2b-partnership-47ae1.firebasestorage.app',
    measurementId: 'G-LEV5LV1YKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX319V0Jp9sQiO6_tpycTcZdHhRkqAUTU',
    appId: '1:701759991705:android:e4e41674af34821e5bad08',
    messagingSenderId: '701759991705',
    projectId: 'b2b-partnership-47ae1',
    storageBucket: 'b2b-partnership-47ae1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-hVOtRwMduoMRSCzcLctrnMXNIBkkA4',
    appId: '1:701759991705:ios:5fec92185dee3fb65bad08',
    messagingSenderId: '701759991705',
    projectId: 'b2b-partnership-47ae1',
    storageBucket: 'b2b-partnership-47ae1.firebasestorage.app',
    iosBundleId: 'com.example.b2bPartenership',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-hVOtRwMduoMRSCzcLctrnMXNIBkkA4',
    appId: '1:701759991705:ios:5fec92185dee3fb65bad08',
    messagingSenderId: '701759991705',
    projectId: 'b2b-partnership-47ae1',
    storageBucket: 'b2b-partnership-47ae1.firebasestorage.app',
    iosBundleId: 'com.example.b2bPartenership',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBTZCGT4VHZFBw5JQmFQqpACq33GPFlqQ',
    appId: '1:701759991705:web:ffc628508e0842b95bad08',
    messagingSenderId: '701759991705',
    projectId: 'b2b-partnership-47ae1',
    authDomain: 'b2b-partnership-47ae1.firebaseapp.com',
    storageBucket: 'b2b-partnership-47ae1.firebasestorage.app',
    measurementId: 'G-CX0QJSY4J4',
  );
}
