const Map<String, String> ar = {
  // General
  "Manage!!": "ادارة!!",
  "add more": "اضافة المزيد",
  "See less": "عرض اقل",
  "See more": "عرض المزيد",
  'Name in English': 'الاسم باللغة الانجليزية',
  'Name in Arabic': "الاسم باللغة العربية",
  "Add": "اضافة",
  "Cancel": "الغاء",
  "More Options:": "اختيارات اخرى:",
  "Delete": "حذف",
  "Edit": "تعديل",
  "Are you sure to delete?": "هل انت متاكد من الحذف",
  "Save": "حفظ",
  "Manage": "ادارة",
  "Name": "الاسم",
  "Phone": "الهاتف",
  "Email": "الايميل",
  "From": "المنشأ",
  "City": "المحافظة",
  "About": "عنه",
  "Services": "الخدمات",
  "Show Service": "عرض الخدمة",
  'Password': "كلمة المرور",
  "Jobs": "الوظائف",
  "View": "مشاهدة",
  "Country": "الدولة",
  "Notifications": "الاشعارات",

  // auth
  "Welcome Back!": "مرحبا بعودتك!",
  "Login": "تسجيل الدخول",
  "Please enter your email and password":
      "الرجاء ادخال البريد الالكتروني وكلمة المرور",
  "Email or Phone": "البريد الالكتروني او رقم الجوال",
  "Email is required": "البريد الالكتروني مطلوب",
  "Password is required": "كلمة المرور مطلوبة",
  "Forget Password?": "نسيت كلمة المرور؟",
  "Forget Password": "نسيت كلمة المرور",
  "Please enter your email to send an OTP to reset your password":
      "الرجاء ادخال البريد الالكتروني لارسال رمز التاكيد لاستعادة كلمة المرور",
  'Email Address': 'البريد الالكتروني',
  'please enter a valid email': 'الرجاء ادخال بريد الكتروني صالح',
  "Send": "ارسال",
  "Reset Password": "استعادة كلمة المرور",
  "Please enter your new Password and Confirm your new Password":
      "الرجاء ادخال كلمة المرور الجديدة وتاكيد كلمة المرور",
  "Verification Code": "رمز التاكيد",
  "We have sent a verification code to your email":
      "لقد ارسلنا رمز التاكيد إلى بريدك الالكتروني",
  'Re Send': 'اعادة الارسال',
  "Login with your email or phone and password":
      "تسجيل الدخول باستخدام البريد الالكتروني او رقم الجوال وكلمة المرور",
  "Enter your email or phone": "ادخل البريد الالكتروني او رقم الجوال",
  "Enter password": "ادخل كلمة المرور",
  "Don't have account?": "ليس لديك حساب؟",
  "Create New": "انشئ حساب جديد",
  "Join as a Client or Service Provider": "انضم كعميل او مقدم خدمة",
  "I'm a client": "انا عميل",
  "Looking for help with a project.": "ابحث عن مساعدة لمشروع",
  "I'm a Service provider": "انا مقدم خدمة",
  "Looking for my favorite work.": "ابحث عن عملي المفضل",
  "Create Account": "انشاء حساب",
  "Already have an account?": "لديك حساب بالفعل؟",
  "Create a New Account": "انشاء حساب جديد",
  "Step": "خطوة",
  "of": "من",
  'Finish': 'انهاء',
  'Next': 'التالي',
  "Enter your full name": "ادخل الاسم الكامل",
  'Enter your email': 'ادخل البريد الالكتروني',
  'Select Country': 'اختر الدولة',
  'Select Sub Category': 'اختر الفئة الفرعية',
  'Select City': 'اختر المدينة',
  'Select Category': 'اختر الفئة الرئيسية',
  "Without country code": "بدون كود الدولة",
  'Provider Type': 'نوع المقدمين',
  "Bio": "نبذة",
  "Description of the Company ....": "وصف الشركة ....",
  "Commercial Register": "السجل التجاري",
  "No file selected   ": "لم يتم اختيار ملف   ",
  "Upload": "رفع",
  "Tax Card": "بطاقة الضريبة",

  // home
  "Home": "الرئسية",
  "Shop": "المتجر",
  "Users": "الاعضاء",
  "Menu": "المزيد",
  "Welcome!": "مرحبا!",
  "Work Categories": "فئات العمل",
  "Provider Types": "اقسام مقدمي الخدمات",
  "Locations": "الاماكن",

  // manage category
  "Category & Subcategory": "الفئات الرئيسية & الفرعية",
  "Categories": "الفئات الرئيسية",
  "Sub Categories": "الفئات الفرعية",
  "Add New Category": "اضافة فئة رئيسية جديدة",
  "Add New Sub Category": "اضافة فئة فرعية جديدة",
  "Delete Category": "حذف الفئة",
  "Edit Category": "تعديل الفئة",
  'Delete Sub Category': "حذف الفئة الفرعية",

  // manage locations
  "Countries & Cities": "الدول والمحافظات",
  "Countries": "الدول",
  "Cities": "المحافظات",
  "Add New Country": "اضافة دولة جديدة",
  "Choose Country": "اختر الدولة",
  "Add New City": "اضافة محافظة جديدة",
  "Delete Country": "حذف الدولة",
  'Delete City': "حذف المحافظة",

  // manage provider types
  "Types": "الانواع",
  "Add New Type": "اضافة نوع جديد",
  'Delete Type': "حذف النوع",

  // manage users
  "Clients": "العملاء",
  "Providers": "مقدمي الخدمات",
  "Admins": "المديرين",

  // manage clients
  "Delete Client": "حذف العميل",

  // manage providers
  "Delete Provider": "خذف مقدم الخدمة",
  "Previous work": "سابقة الاعمال",
  "Reviews": "الاراء",
  "Department": "القسم",
  "Specialization": "التخصص",
  "Commercial Papers": "الاوراق التجارية",
  "Tax Papers": "الاوراق الضريبية",
  "loading...": "تحميل...",
  'View Contact Method': "مشاهدة طرق التواصل",
  "Service List": "عرض الخدمة",
  'Watch Video': "مشاهدة فيديو",
  'Service Ratings': "تقييم الخدمة",
  "Overview": "نبذة عامة",
  "About Seller": "عن البائع",
  'Seller Rating': "تقييم البائع",
  "Seller Since": "بائع منذ",

  // manage admins
  "Delete Admin": "حذف المدير",

  // mange jobs
  "Company": "شركة",
  "Job Title": "المسمي الوظيفي",
  "Contract Type": "نوع العقد",
  "Expiry Date": "تاريخ الانتهاء",
  "Salary": "الراتب",
  "Apply Now": "قدم الان",
  "Position": "الوظيفة",
  "Gender": "الجنس",
  "Skills Required": "المهارات المطلوبة",
  "Experience": "الخبرة",
  "Address": "العنوان",
  "Website": "الموقع الاكتروني",
  "Description": "الوصف",

  // waiting providers
  "Waiting providers": "مقدمي الخدمات قيد الانتظار",
  "Reject": "رفض",
  "Accept": "قبول",

  // shop
  'Add Category': "اضافة فئة",
  'Search...': "بحث ...",
  "Edit Product": "تعديل المنتج",
  "Change Uploaded product (optional)": "تغيير المنتج المرفوع (اختياري)",
  "Accepted files": "الملفات المسموح بها",
  "Title (Arabic)": "العنوان (بالعربية)",
  "enter title (Arabic)": "ادخل العنوان (بالعربية)",
  "Please enter title (Arabic)": "الر جاء ادخل العنوان (بالعربية)",
  "Title (English)": "العنوان (بالانجليزية)",
  "enter title (English)": "ادخل العنوان (بالانجليزية)",
  "Please enter title (English)": "الر جاء ادخل العنوان (بالانجليزية)",
  "Price": "السعر",
  "enter price": "ادخل السعر",
  "Please enter price": "الرجاء ادخل السعر",
  "Discount %": "الخصم ٪",
  "enter discount": "ادخل الخصم",
  "Please enter discount": "الرجاء ادخال الخصم",
  "Description (English)": "الوصف (بالانجليزية)",
  "enter description (English)": "اذخل الوصف (بالانجليزية)",
  "Please enter description (English)": "الرجاء ادخل الوصف (بالانجليزية)",
  "Description (Arabic)": "الوصف (بالعربية)",
  "enter description (Arabic)": "اذخل الوصف (بالعربية)",
  "Please enter description (Arabic)": "الرجاء ادخل الوصف (بالعربية)",
  "enter name (Arabic)": "اذخل الاسم (بالعربية)",
  "Please enter name (Arabic)": "الرجاء ادخل الاسم (بالعربية)",
  "enter name (English)": "اذخل الاسم (بالانجليزية)",
  "Please enter name (English)": "الرجاء ادخل الاسم (بالانجليزية)",
  "No image selected": "لا يوجد صورة",
  "Click to Select image": "اضغط لاختيار واحدة",
  "Add New Product": "اضافة منتج جديد",
  "No cover image selected": "لا يوجد صورة للغطاء",
  "Upload product": "رفع المنتج",

  // orders
  "Order": "الطلب",
  "All Orders": "جميع الطلبات",
  "All": "الكل",
  "Date": "التاريخ",
  "Billed": "مدفوع",
  "Pending": "قيد الانتظار",
  "Delivered": "تم التوصيل",
  "Canceled": "ملغى",
  "No orders found": "لا يوجد طلبات",
  "Approved": "تم الموافقة",
  "Completed": "مكتمل",
  "Order Status": "حالة الطلب",
  "Order Date": "تاريخ الطلب",
  "Order Expiration Date": "تاريخ انتهاء الطلب",
  "Order Total": "مجموع الطلب",
  "Change Order Status": "تغيير حالة الطلب",
  'Select Status': 'اختر الحالة',
  'Update Status': 'تحديث الحالة',
  "Order Items": "اصناف الطلب",

  // setting view
  "Orders": "الطلبات",
  "Other Services": "خدمات اخرى",
  "Personal Information": "معلومات شخصية",
  "Edit Profile": "تعديل الملف الشخصي",
  "Change Password": "تغيير كلمة المرور",
  "Logout?": "تسجيل الخروج",
  "Remove Account": "حذف الحساب",
  "Change Language": "تغيير اللغة",
  "Posts": "المنشورات",
  "Complaints": "الشكاوي",
  "Are you sure you want to remove your account?":
      "هل أنت متأكد أنك تريد حذف حسابك؟",
  'Are you sure you want to logout?': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  "Close": "اغلاق",
  "Call": "اتصال",

  // edit profile
  "uploading image is optional": "تحميل الصورة اختياري",

  // change password
  "Old Password": "كلمة المرور القديمة",
  "New Password": "كلمة المرور الجديدة",
  "Confirm Password": "تاكيد كلمة المرور",
  "Change": "تغيير",
  "Please enter your old, new and confirm new Password":
      "الرجاء ادخل كلمة المرور القديمة والجديدة وتاكيد كلمة المرور",
  "Old Password is required": "كلمة المرور القديمة مطلوبة",
  "New Password is required": "كلمة المرور الجديدة مطلوبة",
  "Confirm Password is required": "تاكيد كلمة المرور مطلوب",
  "Password must be >= 6 letter": "كلمة المرور يجب ان تكون >= 6 حرف",
  "Confirm Password must be >= 6 letter":
      "تاكيد كلمة المرور يجب ان تكون >= 6 حرف",
  "Not match!": "لا يتطابق!",

  // posts
  "FILTERS": "الفلاتر",
  "Category": "التصنيف",
  "Location": "الموقع",
  "Reset": "اعادة تعيين",
  "Freelance Service": "خدمة حرة",
  "Location Filter:": "فلتر الموقع:",
  "Clear Filter": "مسح الفلتر",
  "Apply Filter": "تطبيق الفلتر",
  "Category Filter:": "فلتر التصنيف :",
};
