const Map<String, String> ar = {
  // General
  "Manage!!": "ادارة!!",
  "add more": "اضافة المزيد",
  "See less": "عرض اقل",
  "See more": "عرض المزيد",
  'Name in English': 'الاسم باللغة الانجليزية',
  'Name in Arabic': "الاسم باللغة العربية",
  "Add": "اضافة",
  "Cancel": "الغاء",
  "More Options:": "اختيارات اخرى:",
  "Delete": "حذف",
  "Edit": "تعديل",
  "Are you sure to delete?": "هل انت متاكد من الحذف",
  "Save": "حفظ",
  "Manage": "ادارة",
  "Name": "الاسم",
  "Phone": "الهاتف",
  "Email": "الايميل",
  "From": "المنشأ",
  "City": "المحافظة",
  "About": "عنه",
  "Services": "الخدمات",
  "Show Service": "عرض الخدمة",
  'Password': "كلمة المرور",
  "Jobs": "الوظائف",
  "View": "مشاهدة",
  "Country": "الدولة",
  "Notifications": "الاشعارات",
  "Search ...": "بحث ...",
  "See all": "مشاهدة الكل",

  // auth
  "Welcome Back!": "مرحبا بعودتك!",
  "Login": "تسجيل الدخول",
  "Please enter your email and password":
      "الرجاء ادخال البريد الالكتروني وكلمة المرور",
  "Email or Phone": "البريد الالكتروني او رقم الجوال",
  "Email is required": "البريد الالكتروني مطلوب",
  "Password is required": "كلمة المرور مطلوبة",
  "Forget Password?": "نسيت كلمة المرور؟",
  "Forget Password": "نسيت كلمة المرور",
  "Please enter your email to send an OTP to reset your password":
      "الرجاء ادخال البريد الالكتروني لارسال رمز التاكيد لاستعادة كلمة المرور",
  'Email Address': 'البريد الالكتروني',
  'please enter a valid email': 'الرجاء ادخال بريد الكتروني صالح',
  "Send": "ارسال",
  "Reset Password": "استعادة كلمة المرور",
  "Please enter your new Password and Confirm your new Password":
      "الرجاء ادخال كلمة المرور الجديدة وتاكيد كلمة المرور",
  "Verification Code": "رمز التاكيد",
  "We have sent a verification code to your email":
      "لقد ارسلنا رمز التاكيد إلى بريدك الالكتروني",
  'Re Send': 'اعادة الارسال',
  "Login with your email or phone and password":
      "تسجيل الدخول باستخدام البريد الالكتروني او رقم الجوال وكلمة المرور",
  "Enter your email or phone": "ادخل البريد الالكتروني او رقم الجوال",
  "Enter password": "ادخل كلمة المرور",
  "Don't have account?": "ليس لديك حساب؟",
  "Create New": "انشئ حساب جديد",
  "Join as a Client or Service Provider": "انضم كعميل او مقدم خدمة",
  "I'm a client": "انا عميل",
  "Looking for help with a project.": "ابحث عن مساعدة لمشروع",
  "I'm a Service provider": "انا مقدم خدمة",
  "Looking for my favorite work.": "ابحث عن عملي المفضل",
  "Create Account": "انشاء حساب",
  "Already have an account?": "لديك حساب بالفعل؟",
  "Create a New Account": "انشاء حساب جديد",
  "Step": "خطوة",
  "of": "من",
  'Finish': 'انهاء',
  'Next': 'التالي',
  "Enter your full name": "ادخل الاسم الكامل",
  'Enter your email': 'ادخل البريد الالكتروني',
  'Select Country': 'اختر الدولة',
  'Select Sub Category': 'اختر الفئة الفرعية',
  'Select City': 'اختر المدينة',
  'Select Category': 'اختر الفئة الرئيسية',
  "Without country code": "بدون كود الدولة",
  'Provider Type': 'نوع المقدمين',
  "Bio": "نبذة",
  "Description of the Company ....": "وصف الشركة ....",
  "Commercial Register": "السجل التجاري",
  "No file selected   ": "لم يتم اختيار ملف   ",
  "Upload": "رفع",
  "Tax Card": "بطاقة الضريبة",

  // home
  "Home": "الرئسية",
  "Shop": "المتجر",
  "Users": "الاعضاء",
  "Menu": "المزيد",
  "Welcome!": "مرحبا!",
  "Work Categories": "فئات العمل",
  "Provider Types": "اقسام مقدمي الخدمات",
  "Locations": "الاماكن",
  "Browse categories": "تصفح الفئات",
  "Top Rated Providers": "الاعلي تقييما",
  "Egypt Top Rated": "الاعلي تقييم في مصر",
  "Saudi Arabia Top Rated": 'الاعلي تقييم في السعودية',
  "UAE Top Rated": "الاعلي تقييم في الامارات",
  "Saved": "المحفوظات",
  "Need Custom Service?": "تريد خدمة معينة؟",
  "you can post your custom services\nrequest":
      "يمكنك الان نشر الخدمة\nالتي تحتاجها",
  'Post Now': "نشر الان",
  "Are you looking for a job?": "هل تبحث عن وظيفة؟",
  "See our Employment\nopportunities": "يمكن الان رؤية الوظائف\nالمتاحة عندنا",
  "Shopping?": "هل تريد التسوق؟",
  "Order whatever you need\nfrom the shop": "اطلب كل ما تريد\nمن المتجر",
  'Order Now': "اطلب الان",
  "My Services": "خدماتي",
  "Freelance Services!!": "خدمات حرة!!",
  "You can browse the services available \n for freelance work":
      "يمكنك تصفح الخدمات المتاحة\nللعمل الحر",
  "You can add the available\njob for recruitment":
      "يمكنك اضافة الوظائف \nالمتاحة للتوظيف",
  "Need employees?": "تحتاج موظفين؟",

  // manage category
  "Category & Subcategory": "الفئات الرئيسية & الفرعية",
  "Categories": "الفئات الرئيسية",
  "Sub Categories": "الفئات الفرعية",
  "Add New Category": "اضافة فئة رئيسية جديدة",
  "Add New Sub Category": "اضافة فئة فرعية جديدة",
  "Delete Category": "حذف الفئة",
  "Edit Category": "تعديل الفئة",
  'Delete Sub Category': "حذف الفئة الفرعية",

  // manage locations
  "Countries & Cities": "الدول والمحافظات",
  "Countries": "الدول",
  "Cities": "المحافظات",
  "Add New Country": "اضافة دولة جديدة",
  "Choose Country": "اختر الدولة",
  "Add New City": "اضافة محافظة جديدة",
  "Delete Country": "حذف الدولة",
  'Delete City': "حذف المحافظة",

  // manage provider types
  "Types": "الانواع",
  "Add New Type": "اضافة نوع جديد",
  'Delete Type': "حذف النوع",

  // manage users
  "Clients": "العملاء",
  "Providers": "مقدمي الخدمات",
  "Admins": "المديرين",

  // manage clients
  "Delete Client": "حذف العميل",

  // manage providers
  "Delete Provider": "خذف مقدم الخدمة",
  "Previous work": "سابقة الاعمال",
  "Reviews": "الاراء",
  "Department": "القسم",
  "Specialization": "التخصص",
  "Commercial Papers": "الاوراق التجارية",
  "Tax Papers": "الاوراق الضريبية",
  "loading...": "تحميل...",
  'View Contact Method': "مشاهدة طرق التواصل",
  "Service List": "عرض الخدمة",
  'Watch Video': "مشاهدة فيديو",
  'Service Ratings': "تقييم الخدمة",
  "Overview": "نبذة عامة",
  "About Seller": "عن البائع",
  'Seller Rating': "تقييم البائع",
  "Seller Since": "بائع منذ",

  // manage admins
  "Delete Admin": "حذف المدير",

  // mange jobs
  "Company": "شركة",
  "Job Title": "المسمي الوظيفي",
  "Contract Type": "نوع العقد",
  "Expiry Date": "تاريخ الانتهاء",
  "Salary": "الراتب",
  "Apply Now": "قدم الان",
  "Position": "الوظيفة",
  "Gender": "الجنس",
  "Skills Required": "المهارات المطلوبة",
  "Experience": "الخبرة",
  "Address": "العنوان",
  "Website": "الموقع الاكتروني",
  "Description": "الوصف",
  'Job Applications': "طلبات التوظيف",
  "Accepted": "المقبولة",
  'Rejected': "المرفوضة",
  "MY JOBS": "وظائفي",
  'Search for job seekers': 'البحث عن الباحثين عن عمل',
  'Edit Job': "تعديل الوظيفة",
  'Add New Job': "اضافة وظيفة جديدة",
  "Enter job title": "ادخل المسمى الوظيفي",
  "Enter job description": "ادخل وصف الوظيفة",
  "Required Skills": "المهارات المطلوبة",
  "Enter required skills (comma separated)":
      "أدخل المهارات المطلوبة (مفصولة بفاصلة)",
  "Experience (years)": "الخبرة (بالسنوات)",
  "Enter years of experience": "ادخل سنوات الخبرة",
  "Salary (Optional)": "الراتب (اختياري)",
  "Enter salary": "ادخل الراتب",
  "Full Time": "دوام كامل",
  "Part Time": "دوام جزئي",
  "Intern": "تدريب",
  "Freelance": "عمل حر",
  "Select expiry date": "اختر تاريخ الانتهاء",
  "Please select an expiry date": "الرجاء اختيار تاريخ الانتهاء",
  "Preferred Gender": "الجنس المطلوب",
  "Male": "ذكر",
  "Female": "انثى",
  "Any": "الكل",
  "Delete Job": "حذف الوظيفة",
  "Are you sure you want to\ndelete this job?": "هل انت متأكد من\n حذف الوظيفة",
  "Show Applications": "عرض الطلبات",

  // Job Application
  'Job Application': "طلب توظيف",
  "Years of Experience": "سنين الخبرة",
  "ex: 2": "مثال: 2",
  "Cover Letter": "نقاط هامة",
  "Choose File": "اختيار ملف",
  "Upload Resume": "رفع CV",
  'Submit Application': "ارسال الطلب",
  "enter your answer": "اكتب اجابتك",
  "What makes you the ideal candidate for this position?":
      "ما الذي يجعلك المرشح المثالي لهذا المنصب؟",
  "Expected Salary": "الراتب المتوقع",
  "enter your expected salary (numbers only)":
      "ادخل الراتب المتوقع (الراتب المتوقع)",
  "enter your available to start date": "أدخل تاريخ البدء المتاح لك",
  "Available to Start Date": "متاح لتاريخ البدء",
  "enter your skills": "ادخل مهاراتك",
  "Skills": "المهارات",
  "JOBS": "الوظائف",
  "Select Expiry Date": "اختر تاريخ الانتهاء",
  "Filter": "فلتر",
  "Sub Specialization": "الفئة الفرعية",

  // waiting providers
  "Waiting providers": "مقدمي الخدمات قيد الانتظار",
  "Reject": "رفض",
  "Accept": "قبول",

  // shop
  'Add Category': "اضافة فئة",
  'Search...': "بحث ...",
  "Edit Product": "تعديل المنتج",
  "Change Uploaded product (optional)": "تغيير المنتج المرفوع (اختياري)",
  "Accepted files": "الملفات المسموح بها",
  "Title (Arabic)": "العنوان (بالعربية)",
  "enter title (Arabic)": "ادخل العنوان (بالعربية)",
  "Please enter title (Arabic)": "الر جاء ادخل العنوان (بالعربية)",
  "Title (English)": "العنوان (بالانجليزية)",
  "enter title (English)": "ادخل العنوان (بالانجليزية)",
  "Please enter title (English)": "الر جاء ادخل العنوان (بالانجليزية)",
  "Price": "السعر",
  "enter price": "ادخل السعر",
  "Please enter price": "الرجاء ادخل السعر",
  "Discount %": "الخصم ٪",
  "enter discount": "ادخل الخصم",
  "Please enter discount": "الرجاء ادخال الخصم",
  "Description (English)": "الوصف (بالانجليزية)",
  "enter description (English)": "اذخل الوصف (بالانجليزية)",
  "Please enter description (English)": "الرجاء ادخل الوصف (بالانجليزية)",
  "Description (Arabic)": "الوصف (بالعربية)",
  "enter description (Arabic)": "اذخل الوصف (بالعربية)",
  "Please enter description (Arabic)": "الرجاء ادخل الوصف (بالعربية)",
  "enter name (Arabic)": "اذخل الاسم (بالعربية)",
  "Please enter name (Arabic)": "الرجاء ادخل الاسم (بالعربية)",
  "enter name (English)": "اذخل الاسم (بالانجليزية)",
  "Please enter name (English)": "الرجاء ادخل الاسم (بالانجليزية)",
  "No image selected": "لا يوجد صورة",
  "Click to Select image": "اضغط لاختيار واحدة",
  "Add New Product": "اضافة منتج جديد",
  "No cover image selected": "لا يوجد صورة للغطاء",
  "Upload product": "رفع المنتج",

  // orders
  "Order": "الطلب",
  "All Orders": "جميع الطلبات",
  "All": "الكل",
  "Date": "التاريخ",
  "Billed": "مدفوع",
  "Pending": "قيد الانتظار",
  "Delivered": "تم التوصيل",
  "Canceled": "ملغى",
  "No orders found": "لا يوجد طلبات",
  "Approved": "تم الموافقة",
  "Completed": "مكتمل",
  "Order Status": "حالة الطلب",
  "Order Date": "تاريخ الطلب",
  "Order Expiration Date": "تاريخ انتهاء الطلب",
  "Order Total": "مجموع الطلب",
  "Change Order Status": "تغيير حالة الطلب",
  'Select Status': 'اختر الحالة',
  'Update Status': 'تحديث الحالة',
  "Order Items": "اصناف الطلب",
  "My Orders": "طلباتي",
  "Complete": "مكتمل",

  // setting view
  "Orders": "الطلبات",
  "Other Services": "خدمات اخرى",
  "Personal Information": "معلومات شخصية",
  "Edit Profile": "تعديل الملف الشخصي",
  "Change Password": "تغيير كلمة المرور",
  "Logout?": "تسجيل الخروج",
  "Remove Account": "حذف الحساب",
  "Change Language": "تغيير اللغة",
  "Posts": "المنشورات",
  "Complaints": "الشكاوي",
  "Are you sure you want to remove your account?":
      "هل أنت متأكد أنك تريد حذف حسابك؟",
  'Are you sure you want to logout?': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  "Close": "اغلاق",
  "Call": "اتصال",
  "Logout": "تسجيل الخروج",
  "Shopping": "التسوق",
  "Switch to Client Account": "تحويل الي حساب عميل",
  "Company Type": "نوع الشركة",
  "Mange your Contacts": "ادارة طرق التواصل",
  "Sub Category": "الفئة الفرعية",

  // edit profile
  "uploading image is optional": "تحميل الصورة اختياري",

  // change password
  "Old Password": "كلمة المرور القديمة",
  "New Password": "كلمة المرور الجديدة",
  "Confirm Password": "تاكيد كلمة المرور",
  "Change": "تغيير",
  "Please enter your old, new and confirm new Password":
      "الرجاء ادخل كلمة المرور القديمة والجديدة وتاكيد كلمة المرور",
  "Old Password is required": "كلمة المرور القديمة مطلوبة",
  "New Password is required": "كلمة المرور الجديدة مطلوبة",
  "Confirm Password is required": "تاكيد كلمة المرور مطلوب",
  "Password must be >= 6 letter": "كلمة المرور يجب ان تكون >= 6 حرف",
  "Confirm Password must be >= 6 letter":
      "تاكيد كلمة المرور يجب ان تكون >= 6 حرف",
  "Not match!": "لا يتطابق!",

  // posts
  "FILTERS": "الفلاتر",
  "Category": "التصنيف",
  "Location": "الموقع",
  "Reset": "اعادة تعيين",
  "Freelance Service": "خدمة حرة",
  "Location Filter:": "فلتر الموقع:",
  "Clear Filter": "مسح الفلتر",
  "Apply Filter": "تطبيق الفلتر",
  "Category Filter:": "فلتر التصنيف :",
  "Rating": "التقييم",
  "Rating Filter:": "فلتر التقييم:",
  "Provider": "مقدم خدمة",
  "Saved Provider": "مقدم محفوظ",
  "providers founded": "مقدم موجود",
  'Book Appointment': "حجز موعد",
  'Add Review': "اضافة تعليق",
  'Enter your review': "اكتب رأيك",
  "All Countries": "كل الدول",
  "All Cities": "كل المدن",
  "All Categories": "كل الفئات",
  "All sub Categories": "كل الفئات الفرعية",
  'Add Service': "اضافة خدمة",
  "upload image is (optional)": "تحميل الصورة (اختياري)",
  "enter service name": "ادخل اسم الخدمة",
  "enter service description": "ادخل وصف الخدمة",
  "enter service address": "عنوان الخدمة",
  "Service founded": "خدمة موجودة",
  'Your Posted Services': "خدماتك المنشورة",
  "Price Offers": "عروض الاسعار",
  "Add price offer": "اضافة عرض سعر",
  'Previous': "السابق",
  'Service Features': "ميزات الخدمة",
  "+ Add More": "اضافة المزيد +",
  "- Remove": " حذف -",
  "Feature Title (Arabic)": "عنوان الميزة(بالعربية)",
  "enter feature title in arabic": "ادخل عنوان الميزة بالعربية",
  "Feature Title (English)": "عنوان الميزة (بالانجليزية)",
  "enter feature title in english": "ادخل عنوان الميزة بالانجليزية",

  // contact
  'enter phone number': "ادخل رقم الهاتف",
  'enter email': "ادخل الميل",
  'enter address': "ادخل العنوان",
  'enter telegram': "ادخل رقم التلجرام",
  'enter instagram': "ادخل لينك الانستجرام",
  'enter linkedin': " ادخل لينك لينكد ان",
  'enter website': "ادخل لينك موقعك الالكتروني",
  'enter facebook': "ادخل لينك الفيسبوك",
  "Switch to Provider Account": "تحويل الي حساب مقدم خدمة",
  'My Contacts': "التواصل معي",
  'Instagram': "انستجرام",
  'Facebook': "فيسبوك",
  'Telegram': "تلجرام",
  'Linkedin': "لينكدان",

  // provider profile edit service
  'Edit Service': "تعديل الخدمة",
  'Service Details': "تفاصيل الخدمة",
  'Features': "الخصائص",
  'Title': "اسم الخدمة",
  "enter title": "ادخل عنوان الخدمة",
  "enter service overview": "ادخل نظرة عامة عن الخدمة",
  'Video Link': "رابط الفيديو",
  "enter service video (optional)": "ادخل رابط الفيديو (اختياري)",
  "Arabic Title:": "العنوان باللغة العربية:",
  "English Title:": "العنوان باللغة الانجليزية:",
  'Feature Name (Arabic)': "اسم الميزة باللغة العربية",
  "Enter arabic name": "ادخل الاسم باللغة العربية",
  'Feature Name (English)': "اسم الميزة باللغة الانجليزية",
  "Enter english name": "ادخل الاسم باللغة الانجليزية",
  'Add Price Offer': "اضف عرض سعر",
  'offer price': "سعر العرض",
  'offer description': "وصف العرض",
  'Submit': "ارسال",
  "pending": "قيد الانتظار",
  "You're not logged in": "انت لم تسجل الدخول",
  "Please log in to access this feature.":
      "الرجاء تسجيل الدخول للحصول علي كل الميزات",
};
