const Map<String, String> en = {
  // General
  "Manage!!": "Manage!!",
  "add more": "add more",
  "See less": "See less",
  "See more": "See more",
  'Name in English': 'Name in English',
  'Name in Arabic': 'Name in Arabic',
  "Add": "Add",
  "Cancel": "Cancel",
  "More Options:": "More Options:",
  "Delete": "Delete",
  "Edit": "Edit",
  "Are you sure to delete?": "Are you sure to delete?",
  "Save": "Save",
  "Manage": "Manage",
  "Name": "Name",
  "Phone": "Phone",
  "Email": "Email",
  "From": "From",
  "City": "City",
  "About": "About",
  "Services": "Services",
  "Show Service": "Show Service",
  'Password': 'Password',
  "Jobs": "Jobs",
  "View": "View",
  "Country": "Country",
  "Notifications": "Notifications",
  "Search ...": "Search ...",
  "See all": "See all",

  // auth
  "Welcome Back!": "Welcome Back!",
  "Login": "Login",
  "Login with your email or phone and password":
      "Login with your email or phone and password",
  "Email or Phone": "Email or Phone",
  "Enter your email or phone": "Enter your email or phone",
  "Enter password": "Enter password",
  "Forget Password?": "Forget Password?",
  "Forget Password": "Forget Password",
  "Please enter your email to send an OTP to reset your password":
      "Please enter your email to send an OTP to reset your password",
  'Email Address': 'Email Address',
  'please enter a valid email': 'please enter a valid email',
  "Send": "Send",
  "Reset Password": "Reset Password",
  "Please enter your new Password and Confirm your new Password":
      "Please enter your new Password and Confirm your new Password",
  "Verification Code": "Verification Code",
  "We have sent a verification code to your email":
      "We have sent a verification code to your email",
  'Re Send': 'Re Send',
  "Don't have account?": "Don't have account?",
  "Join as a Client or Service Provider":
      "Join as a Client or Service Provider",
  "I'm a client": "I'm a client",
  "Looking for help with a project.": "Looking for help with a project.",
  "I'm a Service provider": "I'm a Service provider",
  "Looking for my favorite work.": "Looking for my favorite work.",
  "Create Account": "Create Account",
  "Already have an account?": "Already have an account?",
  "Create a New Account": "Create a New Account",
  "Step": "Step",
  "of": "of",
  'Finish': 'Finish',
  'Next': 'Next',
  "Enter your full name": "Enter your full name",
  'Enter your email': 'Enter your email',
  'Select Country': 'Select Country',
  'Select Sub Category': 'Select Sub Category',
  'Select City': 'Select City',
  'Select Category': 'Select Category',
  "Without country code": "Without country code",
  'Provider Type': 'Provider Type',
  "Bio": "Bio",
  "Description of the Company ....": "Description of the Company ....",
  "Commercial Register": "Commercial Register",
  "No file selected   ": "No file selected   ",
  "Upload": "Upload",
  "Tax Card": "Tax Card",

  // home
  "Home": "Home",
  "Shop": "Shop",
  "Users": "Users",
  "Menu": "Menu",
  "Welcome!": "Welcome!",
  "Work Categories": "Work Categories",
  "Provider Types": "Provider Types",
  "Locations": "Locations",
  "Browse categories": "Browse categories",
  "Top Rated Providers": "Top Rated Providers",
  "Egypt Top Rated": "Egypt Top Rated",
  "Saudi Arabia Top Rated": "Saudi Arabia Top Rated",
  "UAE Top Rated": "UAE Top Rated",
  "Saved": "Saved",
  "Need Custom Service?": "Need Custom Service?",
  "you can post your custom services\nrequest":
      "you can post your custom services\nrequest",
  'Post Now': 'Post Now',
  "Are you looking for a job?": "Are you looking for a job?",
  "See our Employment\nopportunities": "See our Employment\nopportunities",
  "Shopping?": "Shopping?",
  "Order whatever you need\nfrom the shop":
      "Order whatever you need\nfrom the shop",
  'Order Now': 'Order Now',

  // manage category
  "Category & Subcategory": "Category & Subcategory",
  "Categories": "Categories",
  "Sub Categories": "Sub Categories",
  "Add New Category": "Add New Category",
  "Add New Sub Category": "Add New Sub Category",
  "Delete Category": "Delete Category",
  "Edit Category": "Edit Category",
  'Delete Sub Category': 'Delete Sub Category',

  // manage locations
  "Countries & Cities": "Countries & Cities",
  "Countries": "Countries",
  "Cities": "Cities",
  "Add New Country": "Add New Country",
  'Choose Country': 'Choose Country',
  "Add New City": "Add New City",
  "Delete Country": "Delete Country",
  'Delete City': 'Delete City',

  // manage provider
  "Types": "Types",
  "Add New Type": "Add New Type",
  'Delete Type': 'Delete Type',

  // manage users
  "Clients": "Clients",
  "Providers": "Providers",
  "Admins": "Admins",

  // manage clients
  "Delete Client": "Delete Client",

  // manage providers
  "Delete Provider": "Delete Provider",
  "Previous work": "Previous work",
  "Reviews": "Reviews",
  "Department": "Department",
  "Specialization": "Specialization",
  "Commercial Papers": "Commercial Papers",
  "Tax Papers": "Tax Papers",
  "loading...": "loading...",
  'View Contact Method': 'View Contact Method',
  "Service List": "Service List",
  'Watch Video': 'Watch Video',
  'Service Ratings': 'Service Ratings',
  "Overview": "Overview",
  "About Seller": "About Seller",
  'Seller Rating': 'Seller Rating',
  "Seller Since": "Seller Since",

  //manage admins
  "Delete Admin": "Delete Admin",

  // jobs
  "Company": "Company",
  "Job Title": "Job Title",
  "Contract Type": "Contract Type",
  "Expiry Date": "Expiry Date",
  "Salary": "Salary",
  "Apply Now": "Apply Now",
  "Position": "Position",
  "Gender": "Gender",
  "Skills Required": "Skills Required",
  "Experience": "Experience",
  "Address": "Address",
  "Website": "Website",
  "Description": "Description",

  // waiting providers
  "Waiting providers": "Waiting providers",
  "Reject": "Reject",
  "Accept": "Accept",

  // shop
  'Add Category': 'Add Category',
  'Search...': 'Search...',
  "Edit Product": "Edit Product",
  "Change Uploaded product (optional)": "Change Uploaded product (optional)",
  "Accepted files": "Accepted files",
  "Title (Arabic)": "Title (Arabic)",
  "enter title (Arabic)": "enter title (Arabic)",
  "Please enter title (Arabic)": "Please enter title (Arabic)",
  "Title (English)": "Title (English)",
  "enter title (English)": "enter title (English)",
  "Please enter title (English)": "Please enter title (English)",
  "Price": "Price",
  "enter price": "enter price",
  "Please enter price": "Please enter price",
  "Discount %": "Discount %",
  "enter discount": "enter discount",
  "Please enter discount": "Please enter discount",
  "Description (English)": "Description (English)",
  "enter description (English)": "enter description (English)",
  "Please enter description (English)": "Please enter description (English)",
  "Description (Arabic)": "Description (Arabic)",
  "enter description (Arabic)": "enter description (Arabic)",
  "Please enter description (Arabic)": "Please enter description (Arabic)",
  "enter name (Arabic)": "enter name (Arabic)",
  "Please enter name (Arabic)": "Please enter name (Arabic)",
  "enter name (English)": "enter name (English)",
  "Please enter name (English)": "Please enter name (English)",
  "No image selected": "No image selected",
  "Click to Select image": "Click to Select image",
  "Add New Product": "Add New Product",
  "No cover image selected": "No cover image selected",
  "Upload product": "Upload product",

  // orders
  "Order": "Order",
  "All Orders": "All Orders",
  "All": "All",
  "Date": "Date",
  "Billed": "Billed",
  "Pending": "Pending",
  "Delivered": "Delivered",
  "Canceled": "Canceled",
  "No orders found": "No orders found",
  "Approved": "Approved",
  "Completed": "Completed",
  "Order Status": "Order Status",
  "Order Date": "Order Date",
  "Order Expiration Date": "Order Expiration Date",
  "Order Total": "Order Total",
  "Change Order Status": "Change Order Status",
  'Select Status': 'Select Status',
  'Update Status': 'Update Status',
  "Order Items": "Order Items",
  "My Orders": "My Orders",
  "Complete": "Complete",

  // setting view
  "Orders": "Orders",
  "Other Services": "Other Services",
  "Personal Information": "Personal Information",
  "Edit Profile": "Edit Profile",
  "Change Password": "Change Password",
  "Logout?": "Logout?",
  "Remove Account": "Remove Account",
  "Change Language": "Change Language",
  "Posts": "Posts",
  "Complaints": "Complaints",
  "Are you sure you want to remove your account?"
      'Are you sure you want to logout?': 'Are you sure you want to logout?',
  "Close": "Close",
  "Call": "Call",
  "Shopping": "Shopping",

  // edit profile
  "uploading image is optional": "uploading image is optional",

  // change password
  "Old Password": "Old Password",
  "New Password": "New Password",
  "Confirm Password": "Confirm Password",
  "Change": "Change",
  "Please enter your old, new and confirm new Password":
      "Please enter your old, new and confirm new Password",
  "Old Password is required": "Old Password is required",
  "New Password is required": "New Password is required",
  "Confirm Password is required": "Confirm Password is required",
  "Password must be >= 6 letter": "Password must be >= 6 letter",
  "Confirm Password must be >= 6 letter":
      "Confirm Password must be >= 6 letter",
  "Not match!": "Not match!",

// posts
  "FILTERS": "FILTERS",
  "Category": "Category",
  "Location": "Location",
  "Reset": "Reset",
  "Freelance Service": "Freelance Service",
  "Location Filter:": "Location Filter:",
  "Clear Filter": "Clear Filter",
  "Apply Filter": "Apply Filter",
  "Category Filter:": "Category Filter:",
  "Rating": "Rating",
  "Rating Filter:": "Rating Filter:",
  "Provider": "Provider",
  "Saved Provider": "Saved Providers",
  "providers founded": "providers founded",
};
